### ISSUE TITLE
if-statements mit mehreren expressions

### ISSUE THREAD

**Issue by cstmth** [JohnnyJayJay/kartoffelskript#2]
So sehen if statements momentan aus:
```
Wenn die andere Bedingung wahr ist, führe den Block {
    Setze x auf y.
    Erhöhe x um 3.
} aus.
```

Wäre folgendes nicht schöner:
```
Wenn die andere Bedinung wahr ist,
    setze x auf y und
    erhöhe x um 3
```
Einrückung freiwillig, damit auch schöne komplexe Sätze möglich sind. Dieses Projekt ist für großes bestimmt, das garantiere ich!

**Comment by Kaktushose** [comment]
1. Das Projekt ist de facto tot
2. Netter Vorschlag, die Verknüpfung mit "und" hat aber nichts mit if statements an sich zu tun

**Comment by cstmth** [comment]
1. Schade, aber habe ich mir schon fast gedacht.
2. Es ging mir auch gar nicht um das und, sondern um die geschweiften Klammern. Die passen halt einfach nicht. Das und war nur eine Nebensache, damit man einen korrekten Satz bilden kann.

**Comment by JohnnyJayJay** [comment]
Hi, danke für den Vorschlag. Ja, leider ist hier seit 2 Jahren nichts mehr passiert, aber verlassen hab ich das Projekt noch nicht. Ich lerne gerade mehr über Programmiersprachen und Typsysteme und habe vor, die Spezifikation noch mal von Grund auf zu überarbeiten und zu vervollständigen (es gibt aktuell leider immer noch ein paar offene Fragen, die grammatisch schwierig sind). Das mit den Blöcken hab ich mir auch schon überlegt. Ich hatte mir sowas hier als Alternative vorgestellt:
```
Wenn a, dann: 
b. 
c. 
Ansonsten:
d.
Anschließend:
# if zu ende
``` 
(whitespace natürlich optional).
Ob das jetzt das schönste Dichter-Deutsch ist, sei mal dahingestellt. Ich will halt hauptsächlich etwas finden, dass sich deterministisch parsen lässt und nicht scheiße aussieht. 

Ich habe mich bisher etwas stark an C-Style Grammatiken bedient, wahrscheinlich ist es aber sinnvoller wenn man sich hier und da etwas eigenes ausdenkt.
